#*****************************************************************
# APOC configuration
#
#*****************************************************************

# Enable imports from the file system
apoc.import.file.enabled=true
# Enable imports from anywhere on the host machine
apoc.import.file.use_neo4j_config=false
# Enable exports to the file system
apoc.export.file.enabled=true
